In [2]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn import preprocessing

In [6]:
from sklearn.ensemble import RandomForestRegressor

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [9]:
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
from sklearn.externals import joblib

In [46]:
filepath = "/home/pk/Eclipse/eclipse-workspace/Python/Wine/winequality-red.csv"
headers = ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"]
df = pd.read_csv(filepath,names = headers)
df.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [12]:
print(df.shape)

(1599, 12)


In [15]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [16]:
y = df.quality

In [17]:
X = df.drop('quality', axis = 1)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123, stratify = y)

In [20]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [23]:
X_train_scaled = scaler.transform(X_train)
print(X_train_scaled.mean(axis = 0))
print(X_train_scaled.std(axis = 0))

[ 1.16664562e-16 -3.05550043e-17 -8.47206937e-17 -2.22218213e-17
  2.22218213e-17 -6.38877362e-17 -4.16659149e-18 -2.54439854e-15
 -8.70817622e-16 -4.08325966e-16 -1.17220107e-15]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [28]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled.mean(axis = 0)

array([ 0.02776704,  0.02592492, -0.03078587, -0.03137977, -0.00471876,
       -0.04413827, -0.02414174, -0.00293273, -0.00467444, -0.10894663,
        0.01043391])

In [29]:
X_test_scaled.std(axis = 0)

array([1.02160495, 1.00135689, 0.97456598, 0.91099054, 0.86716698,
       0.94193125, 1.03673213, 1.03145119, 0.95734849, 0.83829505,
       1.0286218 ])

In [30]:
pipeline = make_pipeline(preprocessing.StandardScaler(), RandomForestRegressor(n_estimators = 100))

In [31]:
pipeline

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

In [32]:
print(pipeline.get_params())

{'memory': None, 'steps': [('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))], 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True), 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=Fals

In [33]:
hyperparameters = {'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [47]:
clf = GridSearchCV(pipeline, hyperparameters, cv = 10)
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decr...mators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [35]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'auto'}

In [36]:
clf.refit

True

In [37]:
y_pred = clf.predict(X_test)

In [38]:
r2_score(y_test, y_pred)

0.4711970458260186

In [39]:
mean_squared_error(y_test, y_pred)

0.34122250000000004

In [41]:
joblib.dump(clf, 'rf_regressor.pkl')

['rf_regressor.pkl']

In [42]:
clf2 = joblib.load('rf_regressor.pkl')

In [43]:
clf2.predict(X_test)

array([6.52, 5.75, 5.08, 5.46, 6.47, 5.82, 4.86, 4.71, 5.03, 5.97, 5.25,
       5.7 , 5.75, 5.07, 5.74, 5.63, 6.73, 5.8 , 5.69, 6.99, 5.4 , 5.63,
       4.98, 5.98, 5.81, 5.05, 5.56, 5.16, 5.9 , 5.96, 5.94, 6.65, 5.97,
       5.02, 4.92, 5.88, 5.03, 5.9 , 5.03, 5.86, 4.93, 5.87, 6.91, 5.18,
       6.11, 5.27, 5.67, 5.52, 5.14, 6.52, 6.1 , 5.24, 5.92, 5.15, 5.64,
       5.78, 5.24, 5.46, 5.08, 5.25, 5.28, 5.09, 5.08, 5.85, 5.95, 5.2 ,
       6.31, 5.06, 5.15, 6.57, 5.75, 5.6 , 5.09, 5.02, 5.44, 5.96, 5.33,
       5.14, 5.38, 5.27, 6.59, 5.47, 6.28, 6.48, 5.1 , 5.83, 6.47, 6.07,
       5.54, 5.95, 5.91, 5.3 , 6.44, 5.71, 5.67, 5.84, 6.76, 6.78, 5.52,
       6.75, 5.06, 5.41, 5.12, 6.6 , 5.05, 4.7 , 5.58, 5.07, 5.68, 5.96,
       5.72, 5.51, 6.12, 5.41, 4.84, 5.23, 5.87, 5.08, 5.01, 5.98, 5.81,
       5.14, 5.87, 6.  , 5.27, 5.34, 5.21, 5.82, 5.46, 5.46, 5.95, 6.29,
       5.14, 5.24, 5.06, 6.51, 5.03, 5.16, 6.87, 5.37, 5.14, 5.1 , 5.82,
       6.06, 5.4 , 5.37, 5.04, 6.65, 5.51, 5.05, 5.