In [1]:
import numpy as np
import pandas as pd

In [32]:
filepath = "/home/pk/Eclipse/eclipse-workspace/Python/Wine/winequality-white.csv"
headers = ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"]
df = pd.read_csv(filepath,sep = ';')
df.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn import preprocessing

In [5]:
from sklearn.ensemble import RandomForestRegressor

In [6]:
from sklearn.metrics import mean_squared_error, r2_score

In [7]:
from sklearn.externals import joblib

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [33]:
df.shape

(4898, 12)

In [34]:
df.describe(include = 'all')

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [35]:
y = df.quality

In [36]:
X = df.drop('quality', axis = 1)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   test_size = 0.2,
                                                   random_state = 23,
                                                   stratify = y)

In [40]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [41]:
X_train_scaled = scaler.transform(X_train)

In [42]:
X_train_scaled.mean(axis = 0)

array([ 3.49105351e-17, -3.80842201e-17, -1.34201538e-16,  1.08812058e-17,
       -4.89654259e-16,  6.75541524e-17,  1.36015072e-16,  2.24751305e-14,
       -1.75006059e-15, -9.24902489e-17, -2.74750445e-16])

In [43]:
X_train_scaled.std(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
X_test_scaled = scaler.transform(X_test)

In [51]:
X_test_scaled.mean(axis = 0)

array([-0.00592955,  0.03007699,  0.04088209,  0.02893478,  0.05095607,
        0.00092669,  0.04393339,  0.04828217,  0.04002316,  0.06055957,
       -0.03148807])

In [47]:
X_test_scaled.std(axis = 0)

array([0.9746616 , 1.01554327, 0.99385526, 1.00279407, 1.05875769,
       1.10986752, 1.0430815 , 1.0015538 , 1.03964973, 0.99610974,
       1.00102751])

In [52]:
pipeline = make_pipeline(preprocessing.StandardScaler(),
                        RandomForestRegressor(n_estimators = 100))

In [54]:
pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler',
   StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('randomforestregressor',
   RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
              max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
              oob_score=False, random_state=None, verbose=0, warm_start=False))],
 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True),
 'randomforestregressor': RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
            max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=N

In [55]:
hyperparameters = {'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [59]:
clf = GridSearchCV(pipeline, hyperparameters, cv = 50)
clf.fit(X_train, y_train)

GridSearchCV(cv=50, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decr...mators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'randomforestregressor__max_features': ['auto', 'sqrt', 'log2'], 'randomforestregressor__max_depth': [None, 5, 3, 1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [60]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'sqrt'}

In [61]:
clf.refit

True

In [62]:
y_pred = clf.predict(X_test)

In [64]:
r2_score(y_test, y_pred)

0.5342233870967743

In [65]:
mean_squared_error(y_test, y_pred)

0.3656375510204082

In [66]:
joblib.dump(clf, 'rf_regressor_white.pkl')

['rf_regressor_white.pkl']